import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,doc,getDoc,setDoc,updateDoc,collection,addDoc,onSnapshot,query,orderBy,runTransaction,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyCgiJ2OLgRf9rep6enYQTohuHGf9PAT6xQ",authDomain:"stars-f6d41.firebaseapp.com",projectId:"stars-f6d41",storageBucket:"stars-f6d41.firebasestorage.app",messagingSenderId:"294339505512",appId:"1:294339505512:web:2c0a8cc124c91d5d6dbadd"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let u,amount,gift,unsub;
$("reg").onclick=async()=>{try{const c=await createUserWithEmailAndPassword(auth,$("email").value,$("pass").value);await setDoc(doc(db,"users",c.user.uid),{email:c.user.email,balance:0,isAdmin:false,createdAt:serverTimestamp()})}catch(e){$("authMsg").textContent=e.message}};
$("login").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value,$("pass").value)}catch(e){$("authMsg").textContent=e.message}};
$("logout").onclick=()=>signOut(auth);
const ADMIN_EMAIL="Brawlstarsk93k@gmail.com";
onAuthStateChanged(auth,x=>{u=x;if(!x){$("auth").hidden=false;$("main").hidden=true;return}$("auth").hidden=true;$("main").hidden=false;onSnapshot(doc(db,"users",u.uid),s=>{const d=s.data()||{};$("bal").textContent=d.balance||0;$("adminBtn").hidden=u.email!==ADMIN_EMAIL});listenTasks()});
function listenTasks(){onSnapshot(query(collection(db,"tasks"),orderBy("createdAt","desc")),s=>{$("taskList").innerHTML="";s.forEach(x=>{let d=x.data(),e=document.createElement("div");e.className="task";e.innerHTML=`<span><b>${safe(d.title)}</b><br><small>${safe(d.description||"")} · +${d.reward} ⭐</small></span><button>Выполнить</button>`;e.querySelector("button").onclick=()=>complete(x.id,d.reward);$("taskList").append(e)})})}
async function complete(id,reward){try{await runTransaction(db,async t=>{let ud=doc(db,"users",u.uid),dd=doc(db,"users",u.uid,"done",id),td=doc(db,"tasks",id),[us,ts,ds]=await Promise.all([t.get(ud),t.get(td),t.get(dd)]);if(!ts.exists()||ds.exists())throw Error("Задание уже выполнено.");t.set(dd,{at:serverTimestamp()});t.update(ud,{balance:(us.data().balance||0)+reward})});alert("Начислено ⭐")}catch(e){alert(e.message)}}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(x=>x.hidden=true);$(b.dataset.page).hidden=false;if(b.dataset.page==="admin")loadOrders()});
$("usePromo").onclick=async()=>{let code=$("promoCode").value.trim();try{await runTransaction(db,async t=>{let ud=doc(db,"users",u.uid),pd=doc(db,"promocodes",code),rd=doc(db,"users",u.uid,"promos",code),[us,ps,rs]=await Promise.all([t.get(ud),t.get(pd),t.get(rd)]);if(!ps.exists())throw Error("Промокод не найден.");let p=ps.data();if(p.type!=="stars")throw Error("Промокод не найден.");if(rs.exists())throw Error("Уже использован.");t.update(ud,{balance:(us.data().balance||0)+p.amount});t.set(rd,{at:serverTimestamp()})});$("promoMsg").textContent="Готово!"}catch(e){$("promoMsg").textContent=e.message}};
$("flow").addEventListener("click",async e=>{let a=e.target.dataset.amount,g=e.target.dataset.g,p=e.target.dataset.p,m=e.target.dataset.m;if(a){amount=+a;if(+$("bal").textContent<amount)return $("flow").innerHTML='<p class="bad">Недостаточно звёзд.</p>';$("flow").innerHTML='<h3>Выберите подарок:</h3><div class="gift"><button data-g="Мишка">🧸 Мишка</button><button data-g="Сердце">❤️ Сердце</button></div>'}else if(g){gift=g;$("flow").innerHTML='<input id="who" placeholder="@username"><button data-p="Анонимно">Анонимно</button><button data-p="Неанонимно">Неанонимно</button>'}else if(p){let who=$("who").value.trim();if(!who)return alert("Введите username");$("flow").innerHTML='<h3>Надпись</h3><button data-m="">Без надписи</button><button data-m="Дефаю От Бомжей💀">Дефаю От Бомжей💀</button><button data-m="Крутой🤙">Крутой🤙</button><button data-m="Привет🧤">Привет🧤</button><button data-m="Пупсик🥺">Пупсик🥺</button>';window.orderData={who,p}}else if(m!==undefined){let{who,p}=window.orderData;try{await runTransaction(db,async t=>{let ud=doc(db,"users",u.uid),us=await t.get(ud),bal=us.data().balance||0;if(bal<amount)throw Error("Недостаточно звёзд.");t.update(ud,{balance:bal-amount});let od=doc(collection(db,"orders"));t.set(od,{userId:u.uid,amount,gift,targetUsername:who,privacy:p,message:m,status:"pending",createdAt:serverTimestamp()})});$("flow").innerHTML='<p class="ok">Заявка отправлена администратору.</p>'}catch(e){alert(e.message)}}});
$("addTask").onclick=async()=>{let title=$("tTitle").value.trim(),description=$("tDesc").value.trim(),reward=+$("tReward").value;if(!title||reward<1)return alert("Заполни поля");await addDoc(collection(db,"tasks"),{title,description,reward,createdAt:serverTimestamp()})};
function loadOrders(){if(unsub)unsub();unsub=onSnapshot(query(collection(db,"orders"),orderBy("createdAt","desc")),s=>{$("orders").innerHTML="";s.forEach(x=>{let d=x.data(),e=document.createElement("div");e.className="order";e.innerHTML=`${d.amount} ⭐ · ${safe(d.gift)} · ${safe(d.targetUsername)} · ${safe(d.privacy)} · ${safe(d.message||"Без надписи")}<br>Статус: ${safe(d.status)} ${d.status==="pending"?'<button>Подтвердить</button>':''}`;let b=e.querySelector("button");if(b)b.onclick=()=>updateDoc(doc(db,"orders",x.id),{status:"approved",approvedAt:serverTimestamp()});$("orders").append(e)})})}
function safe(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
